version: '3.8'

services:
  auystyr_web:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile-dev
    container_name: auystyr_web
    restart: always
    env_file:
      - envs/.env_web_dev
    volumes:
      - ../../backend:/app
      - static:/app/static
      - media:/app/media
      - ../../frontend:/frontend
      - ../../frontend/static:/app/frontend/static
    ports:
      - "8000:8000"
    depends_on:
      auystyr_db:
        condition: service_healthy
    command: sh -c "/entrypoint.sh"

  auystyr_db:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile-db-dev
    image: postgres:15.2-alpine
    container_name: auystyr_db
    restart: always
    env_file:
      - envs/.env_db_dev
    ports:
      - "7777:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  static:
  media: