CREATE USER auystyradmin WITH PASSWORD '@WSX3edc';
CREATE DATABASE auystyrdb;
GRANT ALL PRIVILEGES ON DATABASE auystyrdb TO auystyradmin;
GRANT ALL PRIVILEGES ON SCHEMA public TO auystyradmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO auystyradmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO auystyradmin;
