# Generated by Django 5.0.2 on 2024-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_alter_profile_cover_image_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
