# Generated by Django 5.0.2 on 2024-02-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_profile_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="slug",
        ),
    ]
