# Generated by Django 5.0.2 on 2024-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0008_alter_user_full_name_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "male"), ("female", "female")],
                default="male",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.BooleanField(
                blank=True,
                choices=[("male", "male"), ("female", "female")],
                default="male",
                max_length=100,
                null=True,
            ),
        ),
    ]
