# Generated by Django 5.0.2 on 2024-03-11 12:39

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0010_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefjhigklmnopqrstuvwxyz123",
                length=8,
                max_length=25,
                prefix="",
            ),
        ),
    ]
