# Generated by Django 5.0.2 on 2024-03-10 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_group_grouppost_page"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Event",
        ),
        migrations.RenameModel(
            old_name="GroupPost",
            new_name="EventPost",
        ),
        migrations.AlterModelOptions(
            name="eventpost",
            options={"ordering": ["-date"], "verbose_name_plural": "Event Post"},
        ),
        migrations.RenameField(
            model_name="eventpost",
            old_name="group",
            new_name="event",
        ),
    ]
