# Generated by Django 5.0.2 on 2024-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_group_event_rename_grouppost_eventpost_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"], "verbose_name_plural": "Event"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"], "verbose_name_plural": "Post"},
        ),
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("Only me", "Only me"), ("Everyone", "Everyone")],
                default="everyone",
                max_length=10,
            ),
        ),
    ]
