# Generated by Django 5.0.2 on 2024-02-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.BooleanField(
                choices=[("male", "Male"), ("female", "Female")], max_length=100
            ),
        ),
    ]
