# Generated by Django 5.0.2 on 2024-02-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0009_alter_profile_gender_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "male"), ("female", "female")],
                default="male",
                max_length=100,
                null=True,
            ),
        ),
    ]
