# Generated by Django 5.0.2 on 2024-03-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_bookshelf_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookshelf",
            options={"verbose_name_plural": ["Bookshelves"]},
        ),
    ]
