# Generated by Django 5.0.2 on 2024-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_event_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("Only me", "Only me"), ("Everyone", "Everyone")],
                default="Everyone",
                max_length=10,
            ),
        ),
    ]
