# Generated by Django 5.0.2 on 2024-03-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookexchangerequest',
            old_name='date',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='bookexchangerequest',
            name='receiver_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_post', to='core.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookexchangerequest',
            name='sender_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_post', to='core.post'),
            preserve_default=False,
        ),
    ]
